In [3]:
import numpy as np

In [5]:
# 1 (a)
arr = np.array([1, 2, 3, 6, 4, 5])
rev_arr = arr[::-1]

print("array is ",arr)
print("reversed array is ",rev_arr)

array is  [1 2 3 6 4 5]
reversed array is  [5 4 6 3 2 1]


In [8]:
# 1 (b)
arr = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

flat1 = arr.flatten()
flat2 = arr.ravel()

print("array using flatten(): ",flat1)
print("array using ravel(): ",flat2)

array using flatten():  [1 2 3 2 4 5 1 2 3]
array using ravel():  [1 2 3 2 4 5 1 2 3]


In [ ]:
# 1 (c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print("Arrays are equal:", np.array_equal(arr1, arr2))

Arrays are equal: True


In [10]:
# 1 (d)
x=np.array([1,2,3,4,5,1,2,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])

print("x:",x)
x_cnt=np.bincount(x)
print("Most frequent element in x:", np.argmax(x_cnt))

print("y:",y)
y_cnt=np.bincount(y)
print("Most frequent element in y:", np.argmax(y_cnt))

x: [1 2 3 4 5 1 2 1 1]
Most frequent element in x: 1
y: [1 1 1 2 3 4 2 4 3 3]
Most frequent element in y: 1


In [12]:
# 1 (e)
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg)
total_sum = gfg.sum()
print("Total Sum:", total_sum)
row_sum = gfg.sum(axis=1)
print("Row-wise Sum:", row_sum)
col_sum = gfg.sum(axis=0)
print("Column-wise Sum:", col_sum)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Total Sum: 45
Row-wise Sum: [[14]
 [16]
 [15]]
Column-wise Sum: [[20  9 16]]


In [13]:
# 1 (f)
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

# i. Diagonal Sum
diag_sum = np.trace(n_array)

# ii & iii. Eigenvalues and Eigenvectors
eig_vals, eig_vecs = np.linalg.eig(n_array)

# iv. Inverse
inv = np.linalg.inv(n_array)

# v. Determinant
det = np.linalg.det(n_array)

print("Sum of diagonal elements:", diag_sum)
print("Eigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs)
print("Inverse of matrix:\n", inv)
print("Determinant:", det)

Sum of diagonal elements: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [15]:
# 1(g)
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

multi1 = np.dot(p1, q1)
cov1 = np.cov(p1.flatten(), q1.flatten())
print("Matrix multiplication:", multi1)
print("Covariance matrix:", cov1)

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

multi2 = np.dot(p2, q2)
cov2 = np.cov(p2.flatten(), q2.flatten())
print("Matrix multiplication:", multi2)
print("Covariance matrix:", cov2)

Matrix multiplication: [[16 19]
 [26 31]]
Covariance matrix: [[0.66666667 1.        ]
 [1.         1.66666667]]
Matrix multiplication: [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix: [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [18]:
# 1(h)
from itertools import product


x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner = np.inner(x, y)
outer = np.outer(x.flatten(), y.flatten())
cartesian = np.array([np.concatenate([a, b]) for a, b in product(x, y)])

print("Inner product:", inner)
print("Outer product:", outer)
print("Cartesian product:", cartesian)

Inner product: [[17 52]
 [13 62]]
Outer product: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product: [[ 2  3  4  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  1  5  0]
 [ 3  2  9  5 10  3]]
