In [1]:
import numpy as np

In [8]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
print(array)

abs_arr= np.abs(array)
print("absolute array : ", abs_arr)

flat = array.flatten()

p_flat = np.percentile(flat, [25, 50, 75])
print("\n25th, 50th, 75th Percentile (flattened):", p_flat)
p_col = np.percentile(array, [25, 50, 75], axis=0)
print("Percentile per column:\n", p_col)
p_row = np.percentile(array, [25, 50, 75], axis=1)
print("Percentile per row:\n", p_row)


mean_flat = np.mean(flat)
median_flat = np.median(flat)
std_flat = np.std(flat)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print("\nFlattened - Mean:", mean_flat, ", Median:", median_flat, ", Std Dev:", std_flat)
print("Column-wise - Mean:", mean_col, ", Median:", median_col, ", Std Dev:", std_col)
print("Row-wise - Mean:", mean_row, ", Median:", median_row, ", Std Dev:", std_row)

[[ 1 -2  3]
 [-4  5 -6]]
absolute array :  [[1 2 3]
 [4 5 6]]

25th, 50th, 75th Percentile (flattened): [-3.5 -0.5  2.5]
Percentile per column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentile per row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

Flattened - Mean: -0.5 , Median: -0.5 , Std Dev: 3.8622100754188224
Column-wise - Mean: [-1.5  1.5 -1.5] , Median: [-1.5  1.5 -1.5] , Std Dev: [2.5 3.5 4.5]
Row-wise - Mean: [ 0.66666667 -1.66666667] , Median: [ 1. -4.] , Std Dev: [2.05480467 4.78423336]


In [9]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

print("Original:", a)

floor = np.floor(a)
print("Floor:", floor)

ceil = np.ceil(a)
print("Ceiling:", ceil)

trunc = np.trunc(a)
print("Truncated:", trunc)

rounded = np.round(a)
print("Rounded:", rounded)

Original: [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]
